### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tacolopo**
- Add clarifying information to intro
- Fix hyperlink format for prop88 and add for prop75
- Grammar & spelling fixes

### CODE REVIEW

**Comment by giunatale** [comment]
Hey @tacolopo can you make a format pass and reduce all lines to be less than 79 chars?
Otherwise, I personally think your contribution is great 👍

**Comment by tacolopo** [comment]
Hi @giunatale, the document is now formatted. I wrote a little program to do this formatting in case future contributors want to quickly format off these character requirements:

https://github.com/tacolopo/randpy/blob/main/lessthan79chars.py

**Comment by tacolopo** [comment]
If you come across anything else you want proof read, feel free to tag me @giunatale

**Comment by giunatale** [comment]
Thank you so much!

I would accept your PR btw, but I don't have rights. I am hoping for @jaekwon to address it at some point :)

**Review by jaekwon — COMMENTED** [review]
Thank you!

**Pull request merged**
